name: Test CI number 1

on:
  push:
    branches:
      - 191A010056-191A010055-191A010061
  pull_request:
    branches:
      - 191A010056-191A010055-191A010061

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: hien thi thong bao 1
      run: echo "Hello"
    
    - name: hien thi thong bao 2s
      run: git clone https://github.com/tmaxi-technology/AppliedBioinformatics2023.git
